FROM oven/bun:1 AS build
WORKDIR /app

# Install dependencies
COPY package.json bun.lock* ./
RUN bun install --frozen-lockfile

# Copy source
COPY . .

# Build args for VITE_ env vars (injected at build time)
ARG VITE_SERVER_URL
ARG VITE_PRIVY_APP_ID
ARG VITE_SOLANA_RPC_URL
ARG VITE_SOLANA_NETWORK
ARG VITE_SHOP_TREASURY
ARG VITE_PRIVY_BOT_SIGNER_ID
ARG VITE_BOT_TREASURY_WALLET
ARG VITE_VAPID_PUBLIC_KEY

ENV VITE_SERVER_URL=$VITE_SERVER_URL
ENV VITE_PRIVY_APP_ID=$VITE_PRIVY_APP_ID
ENV VITE_SOLANA_RPC_URL=$VITE_SOLANA_RPC_URL
ENV VITE_SOLANA_NETWORK=$VITE_SOLANA_NETWORK
ENV VITE_SHOP_TREASURY=$VITE_SHOP_TREASURY
ENV VITE_PRIVY_BOT_SIGNER_ID=$VITE_PRIVY_BOT_SIGNER_ID
ENV VITE_BOT_TREASURY_WALLET=$VITE_BOT_TREASURY_WALLET
ENV VITE_VAPID_PUBLIC_KEY=$VITE_VAPID_PUBLIC_KEY

RUN bun run build

# Serve with nginx
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
