// Solana integration layer for the Convex crank service
"use node";
import * as anchor from "@coral-xyz/anchor";
import {
  Connection,
  PublicKey,
  Keypair,
  Transaction,
  VersionedTransaction,
  ComputeBudgetProgram,
  TransactionMessage,
} from "@solana/web3.js";
import { GameConfig, GameRound, DOMIN8_PROGRAM_ID, PDA_SEEDS, BetInfoStruct } from "./types";
import { Buffer } from "buffer";
import bs58 from "bs58";

// Import the IDL type (this will be generated by Anchor)
import type { Domin8Prgm } from "../../target/types/domin8_prgm";
import IDL from "../../target/idl/domin8_prgm.json";

// Simple NodeWallet implementation for server-side use
class NodeWallet implements anchor.Wallet {
  constructor(readonly payer: Keypair) {}

  async signTransaction<T extends Transaction | VersionedTransaction>(tx: T): Promise<T> {
    if (tx instanceof Transaction) {
      tx.partialSign(this.payer);
    } else {
      // VersionedTransaction needs different signing
      tx.sign([this.payer]);
    }
    return tx;
  }

  async signAllTransactions<T extends Transaction | VersionedTransaction>(txs: T[]): Promise<T[]> {
    return txs.map((tx) => {
      if (tx instanceof Transaction) {
        tx.partialSign(this.payer);
      } else {
        tx.sign([this.payer]);
      }
      return tx;
    });
  }

  get publicKey(): PublicKey {
    return this.payer.publicKey;
  }
}

export class SolanaClient {
  private connection: Connection;
  private program: anchor.Program<Domin8Prgm>;
  private provider: anchor.AnchorProvider;
  private authority: Keypair;

  constructor(rpcEndpoint: string, authorityPrivateKey: string) {
    // Initialize connection
    this.connection = new Connection(rpcEndpoint, "confirmed");

    // Create authority keypair from private key
    // Support both JSON array and Base58 formats
    let privateKeyBytes: Uint8Array;

    try {
      const trimmed = authorityPrivateKey.trim();

      if (trimmed.startsWith("[") && trimmed.endsWith("]")) {
        // JSON array format: "[1,2,3,...]"
        privateKeyBytes = new Uint8Array(JSON.parse(trimmed));
      } else {
        // Base58 format (standard Solana wallet export)
        privateKeyBytes = bs58.decode(trimmed);

        // Validate it's a valid Solana keypair (64 bytes)
        if (privateKeyBytes.length !== 64) {
          throw new Error(`Invalid key length: ${privateKeyBytes.length} bytes (expected 64)`);
        }
      }

      this.authority = Keypair.fromSecretKey(privateKeyBytes);
    } catch (error) {
      throw new Error(
        `Failed to parse CRANK_AUTHORITY_PRIVATE_KEY: ${error instanceof Error ? error.message : String(error)}\n` +
          `Supported formats: JSON array [1,2,3,...] or Base58 string (88 chars)\n` +
          `Received (first 50 chars): ${authorityPrivateKey.substring(0, 50)}...`
      );
    }

    // Create provider with NodeWallet
    this.provider = new anchor.AnchorProvider(this.connection, new NodeWallet(this.authority), {
      commitment: "confirmed",
    });

    // Initialize program with real IDL
    this.program = new anchor.Program<Domin8Prgm>(IDL as any, this.provider);
  }

  // Get PDAs for the game accounts (risk-based architecture)
  private getPDAs(roundId?: number) {
    // Config PDA (global configuration)
    const [config] = PublicKey.findProgramAddressSync([PDA_SEEDS.DOMIN8_CONFIG], DOMIN8_PROGRAM_ID);

    // Active game PDA (single PDA that always points to current game)
    const [activeGame] = PublicKey.findProgramAddressSync(
      [PDA_SEEDS.ACTIVE_GAME],
      DOMIN8_PROGRAM_ID
    );

    // console.log("current program id:", this.program.programId.toBase58());
    // console.log("roundId:", roundId);

    // Derive per-game PDA if roundId is provided (for historical lookups)
    let gameRound: PublicKey | undefined;
    if (roundId !== undefined) {
      const roundIdBuffer = Buffer.alloc(8);
      roundIdBuffer.writeBigUInt64LE(BigInt(roundId));
      [gameRound] = PublicKey.findProgramAddressSync(
        [PDA_SEEDS.DOMIN8_GAME, roundIdBuffer],
        DOMIN8_PROGRAM_ID
      );
    }

    return { config, activeGame, gameRound };
  }

  // Get current round ID from Domin8Config
  async getCurrentRoundId(): Promise<number> {
    const { config } = this.getPDAs();

    try {
      const account = await this.program.account.domin8Config.fetchNullable(config);

      if (!account) {
        console.warn("Config account doesn't exist yet");
        return 0;
      }

      return account.gameRound?.toNumber() ?? 0;
    } catch (error) {
      console.error("Error fetching config:", error);
      return 0;
    }
  }

  // Get current game configuration (risk-based architecture)
  async getGameConfig(): Promise<GameConfig | null> {
    const { config } = this.getPDAs();

    try {
      const account = await this.program.account.domin8Config.fetchNullable(config);

      if (!account) {
        console.warn("Config account doesn't exist yet");
        return null;
      }

      return {
        admin: account.admin?.toBase58() ?? "",
        treasury: account.treasury?.toBase58() ?? "",
        gameRound: account.gameRound?.toNumber() ?? 0,
        houseFee: account.houseFee?.toNumber() ?? 0,
        minDepositAmount: account.minDepositAmount?.toNumber() ?? 0,
        maxDepositAmount: account.maxDepositAmount?.toNumber() ?? 0,
        roundTime: account.roundTime?.toNumber() ?? 0,
        lock: account.lock ?? false,
        force: Array.from(account.force || []),
      };
    } catch (error) {
      console.error("Error fetching game config:", error);
      return null;
    }
  }

  // Get current game round state (risk-based architecture)
  async getGameRound(roundId?: number): Promise<GameRound | null> {
    // First get the current round ID if not provided
    const currentRoundId = roundId ?? (await this.getCurrentRoundId());
    // console.log("---->Current round ID:", currentRoundId);

    // Derive the PDA for the current round
    const { gameRound } = this.getPDAs(currentRoundId);

    if (!gameRound) {
      throw new Error("Failed to derive game round PDA");
    }

    try {
      // Fetch account with null check
      const account = await this.program.account.domin8Game.fetchNullable(gameRound);

      // If account doesn't exist or was closed, try previous round
      if (!account) {
        console.log(`Game round ${currentRoundId} account doesn't exist or was closed`);

        // Try previous round if roundId > 0
        if (currentRoundId > 0) {
          console.log(`Attempting to fetch previous round ${currentRoundId - 1}`);
          return this.getGameRound(currentRoundId - 1);
        }
        // No more rounds to check
        return null;
      }

      // console.log("=== Game Round Account ===");
      // console.log(`  Game Round: ${account.gameRound?.toNumber()}`);
      // console.log(`  Status: ${account.status} (0=open, 1=closed)`);
      // console.log(`  Bet Count: ${account.bets?.length ?? 0}`);
      // console.log(`  Total Deposit: ${account.totalDeposit?.toNumber()} lamports`);
      // console.log(`  Winner: ${account.winner?.toBase58() ?? "None"}`);
      // console.log(`  Winning Bet Index: ${account.winningBetIndex?.toNumber() ?? "N/A"}`);
      // console.log("==========================");

      // Transform bets array
      const bets: BetInfoStruct[] = (account.bets || []).map((bet: any) => ({
        walletIndex: bet.walletIndex,
        amount: bet.amount?.toNumber() ?? 0,
        skin: bet.skin,
        position: [bet.position[0], bet.position[1]] as [number, number],
      }));

      return {
        gameRound: account.gameRound?.toNumber() ?? 0,
        startDate: account.startDate?.toNumber() ?? 0,
        endDate: account.endDate?.toNumber() ?? 0,
        totalDeposit: account.totalDeposit?.toNumber() ?? 0,
        rand: account.rand?.toString() ?? "0", // Convert to string to avoid overflow
        map: account.map ?? 0, // Map/background ID (0-255)
        userCount: account.userCount?.toNumber() ?? 0,
        force: Array.from(account.force || []),
        status: account.status ?? 0,
        winner: account.winner ? account.winner.toBase58() : null,
        winnerPrize: account.winnerPrize?.toNumber() ?? 0,
        winningBetIndex: account.winningBetIndex ? account.winningBetIndex.toNumber() : null,
        wallets: (account.wallets || []).map((w: any) => w.toBase58()),
        bets,
        // Computed properties for backward compatibility
        roundId: account.gameRound?.toNumber() ?? 0,
        startTimestamp: account.startDate?.toNumber() ?? 0,
        endTimestamp: account.endDate?.toNumber() ?? 0,
        totalPot: account.totalDeposit?.toNumber() ?? 0,
        betCount: bets.length,
        betAmounts: bets.map((b) => b.amount),
        betSkin: bets.map((b) => b.skin),
        betPosition: bets.map((b) => b.position),
        betWalletIndex: bets.map((b) => b.walletIndex),
      };
    } catch (error) {
      // Game round account doesn't exist yet (no bets placed)
      console.log("No game round exists yet for round", currentRoundId);
      console.log("Error details:", error);
      return null;
    }
  }

  /**
   * Get the current active game state (risk-based architecture)
   * This fetches from the active_game PDA (single source of truth for current game)
   * Use this instead of getGameRound() for real-time game state
   */
  async getActiveGame(): Promise<GameRound | null> {
    const { activeGame } = this.getPDAs();
    console.log("---->Fetching active game from PDA:", activeGame.toBase58());
    try {
      // Fetch account with null check
      const account = await this.program.account.domin8Game.fetchNullable(activeGame);
      if (!account) {
        console.log("No active game exists");
        return null;
      }

      console.log("=== Active Game Account ===");
      console.log(`  Game Round: ${account.gameRound?.toNumber()}`);
      console.log(`  Status: ${account.status} (0=open, 1=closed)`);
      console.log(`  Bet Count: ${account.bets?.length ?? 0}`);
      console.log(`  Total Deposit: ${account.totalDeposit?.toNumber()} lamports`);
      console.log(`  Winner: ${account.winner?.toBase58() ?? "None"}`);
      console.log(`  Winning Bet Index: ${account.winningBetIndex?.toNumber() ?? "N/A"}`);
      console.log("===========================");

      // Transform bets array
      const bets: BetInfoStruct[] = (account.bets || []).map((bet: any) => ({
        walletIndex: bet.walletIndex,
        amount: bet.amount?.toNumber() ?? 0,
        skin: bet.skin,
        position: [bet.position[0], bet.position[1]] as [number, number],
      }));

      return {
        gameRound: account.gameRound?.toNumber() ?? 0,
        startDate: account.startDate?.toNumber() ?? 0,
        endDate: account.endDate?.toNumber() ?? 0,
        totalDeposit: account.totalDeposit?.toNumber() ?? 0,
        rand: account.rand?.toString() ?? "0", // Convert to string to avoid overflow
        map: account.map ?? 0, // Map/background ID (0-255)
        userCount: account.userCount?.toNumber() ?? 0,
        force: Array.from(account.force || []),
        status: account.status ?? 0,
        winner: account.winner ? account.winner.toBase58() : null,
        winnerPrize: account.winnerPrize?.toNumber() ?? 0,
        winningBetIndex: account.winningBetIndex ? account.winningBetIndex.toNumber() : null,
        wallets: (account.wallets || []).map((w: any) => w.toBase58()),
        bets,
        // Computed properties for backward compatibility
        roundId: account.gameRound?.toNumber() ?? 0,
        startTimestamp: account.startDate?.toNumber() ?? 0,
        endTimestamp: account.endDate?.toNumber() ?? 0,
        totalPot: account.totalDeposit?.toNumber() ?? 0,
        betCount: bets.length,
        betAmounts: bets.map((b) => b.amount),
        betSkin: bets.map((b) => b.skin),
        betPosition: bets.map((b) => b.position),
        betWalletIndex: bets.map((b) => b.walletIndex),
      };
    } catch (error) {
      console.log("Error fetching active game:", error);
      return null;
    }
  }

  /**
   * Get the active_game PDA address
   * This is the single PDA that always points to the current game
   */
  getActiveGamePDA(): PublicKey {
    const { activeGame } = this.getPDAs();
    return activeGame;
  }

  // Get current Solana slot
  async getCurrentSlot(): Promise<number> {
    return await this.connection.getSlot("confirmed");
  }

  // End game and lock for winner selection (risk-based architecture)
  // HELIUS OPTIMIZED: Uses confirmed commitment, CU optimization, priority fees, and retry logic
  async endGame(roundId: number): Promise<{ signature: string }> {
    const { config } = this.getPDAs();
    const { gameRound } = this.getPDAs(roundId);

    if (!gameRound) {
      throw new Error("Failed to derive game round PDA");
    }

    console.log(`Ending game for round ${roundId} with Helius optimizations`);

    // Fetch config to get treasury
    const configAccount = await this.program.account.domin8Config.fetch(config);

    // Build the instruction (instead of using .rpc() directly)
    const instruction = await this.program.methods
      .endGame(new anchor.BN(roundId))
      .accounts({
        config,
        game: gameRound,
        admin: this.authority.publicKey,
        treasury: configAccount.treasury,
        oracleQueue: new PublicKey("Cuj97ggrhhidhbu39TijNVqE74xvKJ69gDervRUXAxGh"), // Magic Block queue
        systemProgram: anchor.web3.SystemProgram.programId,
      } as any)
      .instruction();

    // Send using Helius-optimized transaction flow
    const signature = await this.sendOptimizedTransaction(instruction);

    console.log(`Game ${roundId} ended successfully: ${signature}`);
    return { signature };
  }

  // Send prize to winner (risk-based architecture)
  // HELIUS OPTIMIZED: Uses confirmed commitment, CU optimization, priority fees, and retry logic
  async sendPrizeWinner(roundId: number): Promise<{ signature: string }> {
    const { config, gameRound } = this.getPDAs(roundId);

    if (!gameRound) {
      throw new Error("Failed to derive game round PDA");
    }

    // Fetch game to get winner
    const gameAccount = await this.program.account.domin8Game.fetch(gameRound);

    if (!gameAccount.winner) {
      throw new Error("No winner determined yet");
    }

    const winnerPubkey = gameAccount.winner;
    console.log(
      `Sending prize to winner ${winnerPubkey.toBase58()} for round ${roundId} with Helius optimizations`
    );
    console.log(`Prize amount: ${gameAccount.winnerPrize.toString()} lamports`);

    // Build the instruction (instead of using .rpc() directly)
    const instruction = await this.program.methods
      .sendPrizeWinner(new anchor.BN(roundId))
      .accounts({
        config,
        game: gameRound,
        claimer: this.authority.publicKey,
        winner: winnerPubkey,
        systemProgram: anchor.web3.SystemProgram.programId,
      } as any)
      .instruction();

    // Send using Helius-optimized transaction flow
    const signature = await this.sendOptimizedTransaction(instruction);

    console.log(`Prize sent successfully for round ${roundId}: ${signature}`);
    return { signature };
  }

  // Delete old game account and recover rent (admin only)
  // HELIUS OPTIMIZED: Uses confirmed commitment, CU optimization, priority fees, and retry logic
  async deleteGame(roundId: number): Promise<string> {
    const { config, gameRound } = this.getPDAs(roundId);

    if (!gameRound) {
      throw new Error("Failed to derive game round PDA");
    }

    console.log(`Deleting game account for round ${roundId} with Helius optimizations`);

    // Build the instruction (instead of using .rpc() directly)
    const instruction = await this.program.methods
      .deleteGame(new anchor.BN(roundId))
      .accounts({
        config,
        game: gameRound,
        admin: this.authority.publicKey,
      } as any)
      .instruction();

    // Send using Helius-optimized transaction flow
    const signature = await this.sendOptimizedTransaction(instruction);

    console.log(`Game ${roundId} deleted successfully (rent refunded): ${signature}`);
    return signature;
  }

  // Note: VRF functionality removed - risk architecture uses simpler randomness

  // Initialize game configuration (admin only)
  async initializeConfig(
    treasury: string,
    houseFee: number,
    minDepositAmount: number,
    maxDepositAmount: number,
    roundTime: number
  ): Promise<{ signature: string }> {
    const { config } = this.getPDAs();

    try {
      const treasuryPubkey = new PublicKey(treasury);

      const instruction = await this.program.methods
        .initializeConfig(
          treasuryPubkey,
          new anchor.BN(houseFee),
          new anchor.BN(minDepositAmount),
          new anchor.BN(maxDepositAmount),
          new anchor.BN(roundTime)
        )
        .accounts({
          config,
          admin: this.authority.publicKey,
          systemProgram: anchor.web3.SystemProgram.programId,
        } as any)
        .instruction();

      const signature = await this.sendOptimizedTransaction(instruction);

      console.log(`Config initialized successfully: ${signature}`);
      return { signature };
    } catch (error) {
      console.error("Failed to initialize config:", error);
      throw error;
    }
  }

  // Create a new game round (admin only, no bets yet)
  async createGameRound(roundId: number, mapId: number): Promise<{ signature: string }> {
    const { config, activeGame, gameRound } = this.getPDAs(roundId);

    if (!gameRound) {
      throw new Error("Failed to derive game round PDA");
    }

    try {
      const instruction = await this.program.methods
        .createGameRound(new anchor.BN(roundId), mapId)
        .accounts({
          config,
          game: gameRound,
          activeGame,
          user: this.authority.publicKey,
          systemProgram: anchor.web3.SystemProgram.programId,
        } as any)
        .instruction();

      const signature = await this.sendOptimizedTransaction(instruction);

      console.log(`Game round ${roundId} created (no bets yet): ${signature}`);
      return { signature };
    } catch (error) {
      console.error("Failed to create game round:", error);
      throw error;
    }
  }

  // Place a bet in the current game (additional bets after game created)
  async placeBet(
    roundId: number,
    betAmount: number,
    skin: number,
    position: [number, number]
  ): Promise<{ signature: string }> {
    const { config, gameRound } = this.getPDAs(roundId);

    if (!gameRound) {
      throw new Error("Failed to derive game round PDA");
    }

    try {
      const instruction = await this.program.methods
        .bet(new anchor.BN(roundId), new anchor.BN(betAmount), skin, position)
        .accounts({
          config,
          game: gameRound,
          user: this.authority.publicKey,
          systemProgram: anchor.web3.SystemProgram.programId,
        } as any)
        .instruction();

      const signature = await this.sendOptimizedTransaction(instruction);

      console.log(`Bet placed successfully: ${signature}`);
      return { signature };
    } catch (error) {
      console.error("Failed to place bet:", error);
      throw error;
    }
  }

  // Fetch all bets for a specific round (risk-based architecture - bets stored inline)
  async getBetsForRound(roundId: number): Promise<Array<BetInfoStruct & { wallet: string }>> {
    const bets: Array<BetInfoStruct & { wallet: string }> = [];

    // Get game round account
    const { gameRound } = this.getPDAs(roundId);
    if (!gameRound) return bets;

    try {
      const gameRoundAccount = await this.program.account.domin8Game.fetch(gameRound);
      const wallets = gameRoundAccount.wallets || [];
      const betStructs = gameRoundAccount.bets || [];

      // Transform inline bets to include wallet address
      for (const bet of betStructs) {
        const walletPubkey = wallets[bet.walletIndex];
        if (walletPubkey) {
          bets.push({
            walletIndex: bet.walletIndex,
            amount: bet.amount?.toNumber() ?? 0,
            skin: bet.skin,
            position: [bet.position[0], bet.position[1]] as [number, number],
            wallet: walletPubkey.toBase58(),
          });
        }
      }
    } catch (error) {
      console.error(`Error fetching bets for round ${roundId}:`, error);
    }

    return bets;
  }

  /**
   * Get transaction signatures for the domin8 program within a time range
   * Used for event-based bet capture
   */
  async getProgramSignatures(limit: number = 100, before?: string): Promise<string[]> {
    try {
      const signatures = await this.connection.getSignaturesForAddress(
        DOMIN8_PROGRAM_ID,
        {
          limit,
          before,
        },
        "confirmed"
      );

      return signatures.map((sig) => sig.signature);
    } catch (error) {
      console.error("Error fetching program signatures:", error);
      return [];
    }
  }

  /**
   * Parse BetPlaced events from transaction logs
   * Returns bet data extracted from on-chain events
   */
  async parseBetPlacedEvents(signature: string): Promise<
    Array<{
      roundId: number;
      player: string;
      amount: number;
      betCount: number;
      totalPot: number;
      endTimestamp: number;
      isFirstBet: boolean;
      timestamp: number;
      betIndex: number;
    }>
  > {
    try {
      const tx = await this.connection.getTransaction(signature, {
        commitment: "confirmed",
        maxSupportedTransactionVersion: 0,
      });

      if (!tx || !tx.meta) {
        console.log(`Transaction ${signature} not found or has no metadata`);
        return [];
      }

      // Check if transaction succeeded
      if (tx.meta.err) {
        console.log(`Transaction ${signature} failed:`, tx.meta.err);
        return [];
      }

      const events: any[] = [];

      // Parse logs for BetPlaced events
      // Anchor events are emitted as: "Program data: <base64_encoded_event>"
      const logs = tx.meta.logMessages || [];

      for (const log of logs) {
        // Look for anchor event logs
        if (log.includes("Program data:")) {
          try {
            // Extract base64 data
            const dataMatch = log.match(/Program data: (.+)/);
            if (!dataMatch) continue;

            const data = Buffer.from(dataMatch[1], "base64");

            // Decode the event using Anchor's event parser
            const eventData = this.program.coder.events.decode(data.toString("base64"));

            if (eventData && eventData.name === "BetPlaced") {
              events.push({
                roundId: eventData.data.roundId?.toNumber() ?? 0,
                player: eventData.data.player?.toBase58() ?? "",
                amount: eventData.data.amount?.toNumber() ?? 0,
                betCount: eventData.data.betCount ?? 0,
                totalPot: eventData.data.totalPot?.toNumber() ?? 0,
                endTimestamp: eventData.data.endTimestamp?.toNumber() ?? 0,
                isFirstBet: eventData.data.isFirstBet ?? false,
                timestamp: eventData.data.timestamp?.toNumber() ?? 0,
                betIndex: eventData.data.betIndex ?? 0,
              });
            }
          } catch (error) {
            // Not a BetPlaced event, skip
            continue;
          }
        }
      }

      return events;
    } catch (error) {
      console.error(`Error parsing transaction ${signature}:`, error);
      return [];
    }
  }

  /**
   * Get all BetPlaced events from recent transactions
   * This is more efficient than polling individual bet PDAs
   *
   * @param limit - Maximum number of transactions to fetch
   * @param untilSignature - Fetch transactions until this signature (exclusive) - for incremental fetching
   */
  async getAllRecentBetEvents(
    limit: number = 100,
    untilSignature?: string
  ): Promise<
    Array<{
      signature: string;
      roundId: number;
      player: string;
      amount: number;
      betCount: number;
      totalPot: number;
      endTimestamp: number;
      isFirstBet: boolean;
      timestamp: number;
      betIndex: number;
      slot: number;
    }>
  > {
    try {
      // Get recent signatures, optionally starting from a specific signature
      const options: any = { limit };
      if (untilSignature) {
        options.until = untilSignature; // Fetch transactions until (not including) this signature
      }

      const signatureInfos = await this.connection.getSignaturesForAddress(
        DOMIN8_PROGRAM_ID,
        options,
        "confirmed"
      );

      const allEvents: any[] = [];

      // Parse each transaction for BetPlaced events
      for (const sigInfo of signatureInfos) {
        const events = await this.parseBetPlacedEvents(sigInfo.signature);

        for (const event of events) {
          allEvents.push({
            signature: sigInfo.signature,
            slot: sigInfo.slot,
            ...event,
          });
        }
      }

      console.log(
        `Found ${allEvents.length} BetPlaced events from ${signatureInfos.length} transactions`
      );
      return allEvents;
    } catch (error) {
      console.error("Error fetching recent bet events:", error);
      return [];
    }
  }

  // Note: VRF helper methods removed - VRF is now handled directly by the smart contract
  // via ORAO VRF integration in create_game instruction

  // Confirm transaction with retry logic
  async confirmTransaction(signature: string, maxRetries: number = 3): Promise<boolean> {
    let retries = 0;

    while (retries < maxRetries) {
      try {
        const result = await this.connection.confirmTransaction(signature, "confirmed");

        if (result.value.err) {
          console.error(`Transaction failed: ${signature}`, result.value.err);
          return false;
        }

        return true;
      } catch (error) {
        retries++;
        console.warn(
          `Transaction confirmation retry ${retries}/${maxRetries} for ${signature}:`,
          error
        );

        if (retries >= maxRetries) {
          console.error(
            `Transaction confirmation failed after ${maxRetries} retries: ${signature}`
          );
          return false;
        }

        // Wait before retry
        await new Promise((resolve) => setTimeout(resolve, 2000));
      }
    }

    return false;
  }

  // Health check - test connection and authority (risk-based architecture)
  async healthCheck(): Promise<{ healthy: boolean; message: string; slot?: number }> {
    try {
      // Test connection
      const slot = await this.getCurrentSlot();

      // Test authority balance
      const balance = await this.connection.getBalance(this.authority.publicKey);
      if (balance < 10_000_000) {
        // Less than 0.01 SOL
        return {
          healthy: false,
          message: `Authority balance too low: ${balance / 1e9} SOL`,
          slot,
        };
      }

      // Test if config account exists
      const { config } = this.getPDAs();
      await this.program.account.domin8Config.fetch(config);

      // Note: We don't check activeGame/gameRound here since they may not exist yet (no bets placed)

      return {
        healthy: true,
        message: "All systems healthy",
        slot,
      };
    } catch (error) {
      return {
        healthy: false,
        message: `Health check failed: ${error instanceof Error ? error.message : String(error)}`,
      };
    }
  }

  // ========================================
  // HELIUS TRANSACTION OPTIMIZATION HELPERS
  // ========================================

  /**
   * Get dynamic priority fee estimate using Helius Priority Fee API
   * HELIUS BEST PRACTICE: Use serialized transaction method for most accurate estimates
   *
   * @param instruction - The instruction to estimate fee for
   * @param payer - The payer public key
   * @returns Priority fee in microlamports/CU, or fallback value if API fails
   */
  private async getPriorityFeeEstimate(
    instruction: anchor.web3.TransactionInstruction,
    payer: PublicKey
  ): Promise<number> {
    try {
      // HELIUS BEST PRACTICE #1: Use 'confirmed' commitment for latest blockhash
      const { blockhash } = await this.connection.getLatestBlockhash("confirmed");

      // Create temp transaction for fee estimation
      const tempMessage = new TransactionMessage({
        payerKey: payer,
        recentBlockhash: blockhash,
        instructions: [instruction],
      }).compileToV0Message();

      const tempTx = new VersionedTransaction(tempMessage);
      const serializedTx = bs58.encode(tempTx.serialize());

      // Call Helius Priority Fee API
      const response = await fetch(this.connection.rpcEndpoint, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          jsonrpc: "2.0",
          id: "1",
          method: "getPriorityFeeEstimate",
          params: [
            {
              transaction: serializedTx,
              options: {
                recommended: true, // Use Helius recommended fee for staked connections
              },
            },
          ],
        }),
      });

      const data = await response.json();

      if (data.result?.priorityFeeEstimate) {
        // Add 20% safety buffer to recommended fee (Helius recommendation)
        const estimatedFee = Math.ceil(data.result.priorityFeeEstimate * 1.2);
        console.log(`Priority fee estimate: ${estimatedFee} microlamports/CU`);
        return estimatedFee;
      }

      // Fallback to medium priority if result not found
      console.warn("Priority fee API returned no estimate, using fallback");
      return 50_000; // 50k microlamports - medium priority
    } catch (error) {
      console.warn("Priority fee estimation failed, using fallback:", error);
      return 50_000; // Fallback fee - medium priority
    }
  }

  /**
   * Simulate transaction and optimize compute units
   * HELIUS BEST PRACTICE: Simulate with high CU limit, then use actual consumption + 10% buffer
   *
   * @param instruction - The instruction to simulate
   * @param payer - The payer public key
   * @param blockhash - Recent blockhash
   * @returns Optimized compute unit limit
   */
  private async simulateAndOptimizeComputeUnits(
    instruction: anchor.web3.TransactionInstruction,
    payer: PublicKey,
    blockhash: string
  ): Promise<number> {
    try {
      // HELIUS BEST PRACTICE: Simulate with 1.4M CU limit to ensure simulation succeeds
      const testInstructions = [
        ComputeBudgetProgram.setComputeUnitLimit({ units: 1_400_000 }),
        instruction,
      ];

      const testMessage = new TransactionMessage({
        payerKey: payer,
        recentBlockhash: blockhash,
        instructions: testInstructions,
      }).compileToV0Message();

      const testTransaction = new VersionedTransaction(testMessage);

      const simulation = await this.connection.simulateTransaction(testTransaction, {
        replaceRecentBlockhash: true,
        sigVerify: false,
      });

      if (simulation.value.err) {
        console.warn("Simulation returned error:", simulation.value.err);
        // Return conservative estimate if simulation fails
        return 200_000;
      }

      if (!simulation.value.unitsConsumed) {
        console.warn("Simulation did not return unitsConsumed");
        return 200_000;
      }

      // HELIUS BEST PRACTICE: Add 10% buffer to compute units
      const optimizedCU =
        simulation.value.unitsConsumed < 1000
          ? 1000
          : Math.ceil(simulation.value.unitsConsumed * 1.1);

      console.log(
        `Optimized compute units: ${optimizedCU} (consumed: ${simulation.value.unitsConsumed})`
      );
      return optimizedCU;
    } catch (error) {
      console.warn("Compute unit simulation failed:", error);
      // Return conservative fallback
      return 200_000;
    }
  }

  /**
   * Build and send an optimized transaction with Helius best practices
   *
   * @param instruction - The instruction to send
   * @param extraSigners - Additional signers (if any)
   * @returns Transaction signature
   */
  private async sendOptimizedTransaction(
    instruction: anchor.web3.TransactionInstruction,
    extraSigners: Keypair[] = []
  ): Promise<string> {
    // HELIUS BEST PRACTICE #1: Use 'confirmed' commitment for latest blockhash
    const { blockhash, lastValidBlockHeight } =
      await this.connection.getLatestBlockhash("confirmed");

    // HELIUS BEST PRACTICE #2: Simulate to optimize compute units
    const computeUnits = await this.simulateAndOptimizeComputeUnits(
      instruction,
      this.authority.publicKey,
      blockhash
    );

    // HELIUS BEST PRACTICE #3: Get dynamic priority fee estimate
    const priorityFee = await this.getPriorityFeeEstimate(instruction, this.authority.publicKey);

    // Build final optimized transaction with compute budget instructions
    // Note: Compute budget instructions MUST come first
    const finalInstructions = [
      ComputeBudgetProgram.setComputeUnitLimit({ units: computeUnits }),
      ComputeBudgetProgram.setComputeUnitPrice({ microLamports: priorityFee }),
      instruction,
    ];

    const finalMessage = new TransactionMessage({
      payerKey: this.authority.publicKey,
      recentBlockhash: blockhash,
      instructions: finalInstructions,
    }).compileToV0Message();

    const finalTransaction = new VersionedTransaction(finalMessage);

    // Sign transaction
    const allSigners = [this.authority, ...extraSigners];
    finalTransaction.sign(allSigners);

    // HELIUS BEST PRACTICE #4 & #5: Send with skipPreflight and implement custom retry logic
    let signature: string | null = null;
    const maxRetries = 3;

    for (let attempt = 0; attempt < maxRetries; attempt++) {
      try {
        // Check if blockhash is still valid
        const currentBlockHeight = await this.connection.getBlockHeight("confirmed");
        if (currentBlockHeight > lastValidBlockHeight) {
          throw new Error("Blockhash expired, need to rebuild transaction");
        }

        // Send with skipPreflight: true (Helius best practice)
        signature = await this.connection.sendRawTransaction(finalTransaction.serialize(), {
          skipPreflight: true,
          maxRetries: 0, // We handle retries ourselves
        });

        // Confirm transaction with polling
        const confirmed = await this.confirmTransactionWithPolling(signature, lastValidBlockHeight);

        if (confirmed) {
          console.log(`Transaction confirmed on attempt ${attempt + 1}: ${signature}`);
          break;
        } else {
          console.warn(`Transaction confirmation timeout on attempt ${attempt + 1}`);
        }
      } catch (error: any) {
        console.warn(`Transaction attempt ${attempt + 1} failed:`, error.message);
        if (attempt === maxRetries - 1) {
          throw error;
        }
        // Exponential backoff
        await new Promise((resolve) => setTimeout(resolve, 1000 * (attempt + 1)));
      }
    }

    if (!signature) {
      throw new Error("All retry attempts failed");
    }

    return signature;
  }

  /**
   * Confirm transaction with polling and blockhash expiry check
   * HELIUS BEST PRACTICE: Implement robust confirmation polling
   *
   * @param signature - Transaction signature
   * @param lastValidBlockHeight - Last valid block height for the transaction
   * @returns True if confirmed, false otherwise
   */
  private async confirmTransactionWithPolling(
    signature: string,
    lastValidBlockHeight: number
  ): Promise<boolean> {
    const timeout = 30000; // 30 seconds (generous for crank operations)
    const interval = 2000; // 2 seconds
    const startTime = Date.now();

    while (Date.now() - startTime < timeout) {
      try {
        const statuses = await this.connection.getSignatureStatuses([signature]);
        const status = statuses?.value?.[0];

        if (status) {
          if (status.err) {
            console.error("Transaction failed with error:", status.err);
            return false;
          }

          if (
            status.confirmationStatus === "confirmed" ||
            status.confirmationStatus === "finalized"
          ) {
            return true;
          }
        }

        // Check if blockhash expired
        const currentBlockHeight = await this.connection.getBlockHeight("confirmed");
        if (currentBlockHeight > lastValidBlockHeight) {
          console.warn("Blockhash expired during confirmation polling");
          return false;
        }
      } catch (error) {
        console.warn("Status check failed:", error);
      }

      await new Promise((resolve) => setTimeout(resolve, interval));
    }

    console.warn("Transaction confirmation timeout");
    return false;
  }
}
